# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{goldberg}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Srushti Ambekallu"]
  s.date = %q{2010-11-29}
  s.email = %q{srushti@c42.in}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/goldberg.rb",
    "lib/goldberg/init.rb",
    "lib/goldberg/job.rb"
  ]
  s.homepage = %q{http://c42.in/open_source}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = nil

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, ["= 1.1.0"])
      s.add_runtime_dependency(%q<sinatra_more>, [">= 0"])
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, ["= 1.1.0"])
      s.add_dependency(%q<sinatra_more>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, ["= 1.1.0"])
    s.add_dependency(%q<sinatra_more>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

