#! /bin/bash


if [ $# == 0 ]; then
  echo "This script is meant to be run by goldberg"
  echo "goldberg-build project ruby project.code_path build_log_path artefacts_path project.build_command"
  exit 1
fi

project="$1" && shift
ruby="$1" && shift
code_path="$1" && shift
build_log_path="$1" && shift
artifacts_path="$1" && shift
command="$@"

export BUNDLE_GEMFILE=""
export RUBYOPT=""
export RAILS_ENV=""
export BUILD_ARTIFACTS="$artifacts_path"
export BUILD_ARTEFACTS="$artifacts_path"

rvm_script_sourced()
{
  if [ -e ~/.rvm/scripts/rvm ]; then
    source ~/.rvm/scripts/rvm
  elif [ -e /usr/local/rvm/scripts/rvm]; then
    source /usr/local/rvm/scripts/rvm
  else
    return -1
  fi
}

if rvm_script_sourced ; then 
      rvm use --create "$ruby@global"
      (gem list | grep bundler) || gem install bundler
      rvm rvmrc trust $code_path
fi

cd $code_path
      build_command = "#{environment_string} #{project.build_command}"
      full_command = [RVM.use_script(ruby, "goldberg-#{project.name}"), go_to_project_path, build_command].compact.join(' ; ')
      output_redirects = "1>>#{build_log_path} 2>>#{build_log_path}"
      execute_async("(#{full_command}) #{output_redirects}")

